"""
sensitivity_analysis.py
=======================

Reactivity-feedback sensitivity scan on the GCR model defined in GCR_test.py.

For each of five independent variables the script records k_eff at baseline
and at a series of perturbed states:

    1. fuel temperature: ΔT in {-50, -25, -10, -5, +5, +10, +25, +50} K,
       applied additively to every fuel material (fuel_inner / fuel_outer,
       all axial layers). Per-layer baseline temperatures are unchanged
       relative to each other; only the common offset changes.

    2. hydrogen propellant density: fractional deltas
       {-3, -2, -1, +1, +2, +3} %, applied multiplicatively to every H2
       propellant material (main channel + layers + header + liner + tori).

    3. cavity power: fractional deltas {-10, -5, +5, +10} %, applied by
       swapping in a propellant profile pre-computed at the perturbed power
       AND scaling GCRConfig.Q_total by the same factor. The perturbed
       profile changes the per-layer H2 temperature and density; the scaled
       Q_total feeds into GCR.fuel_temperature_from_h2() so the radiation-
       equilibrium fuel temperature also shifts. Profiles are expected at
           settings/h2_density_profile_power_{sign}{pct:02d}pct.npz
       and are generated by hydrogen_propellant_profile.py.

    4. fuel density: fractional deltas {-10, -5, +5, +10} %, applied
       multiplicatively to every fuel material (fuel_inner / fuel_outer,
       all axial layers) WITHOUT touching their temperature. This isolates
       the pure number-density component of the fuel feedback, with no
       cross-section interpolation effects in play.

    5. BeO reflector temperature: ΔT in {-200, -100, -50, +50, +100, +200} K,
       applied additively to the single 'BeO' material that fills the
       inter-cavity moderator slabs and the top cap. The bulk density is
       held constant -- moderator thermal expansion is small compared to
       the S(alpha, beta) temperature effect that dominates the reactivity
       response.

    6. H2 propellant temperature: ΔT in {-200, -100, -50, +50, +100, +200} K,
       applied additively to every H2 propellant material (main channel +
       layers + header + liner + tori). Per-layer baseline temperatures are
       unchanged relative to each other; only the common offset changes.
       Like the fuel, hydrogen is a gas, so the realistic coupled feedback
       follows rho * T = const at constant pressure -- enable this with
       COUPLE_DENSITY_TO_H2_T. Set it to False to isolate the
       cross-section / thermal-scattering-kernel temperature effect.

Reactivity change:
                 rho = (k - k_ref) / (k * k_ref)        [pcm when * 1e5]

From the sweep the script fits a weighted least-squares line through the
(delta, rho) points and reports:

    alpha_T     in pcm per kelvin                (fuel temperature)
    alpha_rho   in pcm per % H2 density change
    alpha_Q     in pcm per % cavity-power change
    alpha_rho_F in pcm per % fuel density change
    alpha_BeO   in pcm per kelvin                (BeO reflector temperature)
    alpha_T_H2  in pcm per kelvin                (H2 propellant temperature)

with slope uncertainties from the weighted-fit covariance.

Placement: drop this file next to GCR.py and run
           `python sensitivity_analysis.py`.
Runtime:   1 baseline + 8 fuel-T + 6 H2-rho = 15 OpenMC runs. Budget several
           hours at 50 batches × 15,000 particles.

Fuel-temperature coupling assumption
------------------------------------
The fuel is a gas. At constant pressure an ideal gas satisfies rho * T = const,
so heating the fuel also thins it. The realistic GCR temperature feedback is
therefore the *combined* Doppler-plus-density effect -- this is the default.

Set COUPLE_DENSITY_TO_FUEL_T = False to hold fuel density fixed and measure
a pure Doppler coefficient instead.

Cross-section note
------------------
OpenMC interpolates cross sections in sqrt(T) between the processed library
temperatures. For small ΔT at 15-20 kK, the response you measure is the
slope of that interpolation, not an independent Doppler measurement. The
fit is still meaningful as "the coefficient embedded in the library as
used", but interpret it accordingly.
"""

import os
import json
from dataclasses import replace
import numpy as np
import openmc

import argparse
import os
import sys

# Allow running from the repository root without installing the package
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from gcr import GCRConfig, GCR
from gcr import plotting, tallies
from gcr.analysis.mass_estimate import print_u233_mass_estimate
from gcr.analysis.four_factors import add_four_factor_tallies

# ---------------------------------------------------------------------------
# Scan configuration
# ---------------------------------------------------------------------------

# Absolute fuel-temperature shifts in kelvin. Applied additively to every
# fuel material, so per-layer baseline differences are preserved.
FUEL_T_DELTAS_K = [-5000, -2000, -1000, +1000, +2000, +5000]

# H2 propellant density perturbations as fractional change.
H2_RHO_DELTAS = [-0.10, -0.05, +0.05, +0.10]


# Fuel density perturbations as fractional change. Applied multiplicatively
# to every fuel material (fuel_inner / fuel_outer, all axial layers) without
# touching their temperatures, so this isolates the pure number-density
# contribution to the fuel feedback.
FUEL_RHO_DELTAS = [-0.10, -0.05, +0.05, +0.10]

# Absolute BeO-reflector-temperature shifts in kelvin. Applied additively to
# the single BeO material (which fills the inter-cavity moderator slabs and
# the top cap). Density is held fixed -- thermal expansion of solid BeO is
# small compared to the S(alpha, beta) temperature effect.
#BEO_T_DELTAS_K = [-598, -498, -398, -298, -198, -48, +102, +302, +352, +402, +552, +802]
BEO_T_DELTAS_K = [-198, -48, +102, +302, +352, +402, +552, +802]

# Absolute H2-propellant-temperature shifts in kelvin. Applied additively to
# every propellant-H2 material (main channel + per-layer slices + header +
# liner + tori), so per-layer baseline differences along the channel are
# preserved. If COUPLE_DENSITY_TO_H2_T is True, density tracks T as
# rho * T = const (ideal-gas expansion at constant channel pressure).
H2_T_DELTAS_K = [-1000, -600, -200, -100, +100, +200, +300, +400, +600, +1000]

# Fractional change of every fuel-cloud radius (R0, R1, R2 scale together;
# R3 = transparent wall stays fixed). delta = delta_R / R2_baseline [mm/mm].
FUEL_RADIUS_DELTAS = [-0.10, -0.05, +0.05, +0.10]
FUEL_RADIUS_DELTAS = [+0.05, +0.10]

RESULTS_DIR = 'sensitivity_results'
RUNS_DIR    = 'sensitivity_runs'

# True  -> call core.add_kinetics_tally() before each run so that IFP-based
#          β_eff (total + 6-group) and Λ_eff are recorded in the statepoint.
#          Requires the cross-section library to carry delayed-neutron data.
# False -> skip kinetics tallies (faster, smaller statepoints).
COLLECT_KINETIC_PARAMS = True

# Baseline configuration. Mirrors main() in GCR_test.py -- edit if you move
# the cross-section library or change the layer count.
BASE_CONFIG_KWARGS = dict(
    cross_sections_dir='libraries_xs/jeff40_hdf5',
    n_axial_layers=10,
    h2_density_profile_path='settings/h2_density_profile.npz',
)

# Monte Carlo statistics (applied to every case in the sweep)
N_BATCHES   = 250
N_INACTIVE  = 50
N_PARTICLES = 500_000
# ---------------------------------------------------------------------------
# Material classification
# ---------------------------------------------------------------------------

def _is_fuel(mat):
    # set_materials() names the single-layer fuel 'fuel' / 'fuel_outer'.
    # _create_layered_fuel_materials() names layered ones
    # 'fuel_inner_layer_k' / 'fuel_outer_layer_k'.
    name = mat.name or ''
    return (name == 'fuel'
            or name.startswith('fuel_inner')
            or name.startswith('fuel_outer'))


def _is_propellant_h2(mat):
    name = mat.name or ''
    return (name.startswith('hydrogen_layer')
        )


def _is_beo_reflector(mat):
    # set_materials() creates a single material called 'BeO' that fills the
    # inter-cavity moderator slabs and the top cap.
    name = mat.name or ''
    return name == 'BeO'


def _unique_materials(core):
    """Yield each material object once, de-duplicating by id().

    _create_layered_fuel_materials() aliases 'fuel_inner' / 'fuel_outer' in
    core.materials to the layer-0 objects, so the same object appears under
    two dict keys. Without the de-dup a naive loop perturbs layer 0 twice.
    """
    seen = set()
    for mat in core.materials.values():
        if id(mat) in seen:
            continue
        seen.add(id(mat))
        yield mat


# Perturbation

def perturb_fuel_temperature(core, dT_kelvin):
    """Shift every fuel material's temperature by dT_kelvin (additive).
    """
    for mat in _unique_materials(core):
        if not _is_fuel(mat):
            continue

        T_old = mat.temperature
        T_new = T_old + dT_kelvin
        mat.temperature = T_new


def perturb_h2_density(core, factor):
    """Scale density of every propellant-H2 material by `factor`."""
    for mat in _unique_materials(core):
        if not _is_propellant_h2(mat):
            continue
        if mat.density_units != 'g/cm3':
            raise RuntimeError(
                f'H2 material {mat.name!r} has density_units='
                f'{mat.density_units!r}; expected g/cm3.'
            )
        mat.set_density('g/cm3', mat.density * factor)


def perturb_fuel_density(core, factor):
    """Scale density of every fuel material by `factor`, leaving temperature alone."""
    for mat in _unique_materials(core):
        if not _is_fuel(mat):
            continue
        if mat.density_units != 'g/cm3':
            raise RuntimeError(
                f'Fuel material {mat.name!r} has density_units='
                f'{mat.density_units!r}; expected g/cm3.'
            )
        mat.set_density('g/cm3', mat.density * factor)


def perturb_beo_temperature(core, dT_kelvin):
    """Shift the BeO reflector/moderator material's temperature by dT_kelvin."""
    for mat in _unique_materials(core):
        if not _is_beo_reflector(mat):
            continue
        T_old = mat.temperature
        T_new = T_old + dT_kelvin
        mat.temperature = T_new


def perturb_h2_temperature(core, dT_kelvin):
    """Shift every propellant-H2 material's temperature by dT_kelvin.

    Applies to the main channel material, all axial-layer slices, the header,
    the liner, and the tori -- per-layer baseline differences along the
    channel are preserved.
    """
    for mat in _unique_materials(core):
        if not _is_propellant_h2(mat):
            continue

        T_old = mat.temperature
        T_new = T_old + dT_kelvin
        mat.temperature = T_new


def print_material_temperatures(core, label=''):
    """Print temperature (and density) of every unique material.

    Called inside run_case() right after the perturbation has been applied,
    so the printed values are exactly what OpenMC will see for this case.
    Materials are grouped by the same classifiers used for perturbations
    (fuel / H2 propellant / BeO reflector / other), so it is easy to scan
    the relevant block and verify a sweep landed where expected.

    Density is shown alongside temperature because several perturbations
    couple the two (h2_rho, fuel_rho, optionally fuel_T and h2_T via the
    COUPLE_DENSITY_TO_*_T flags).
    """
    header = f'  Material state{(": " + label) if label else ""}:'
    print(header)

    fuel_mats, h2_mats, beo_mats, other_mats = [], [], [], []
    for mat in _unique_materials(core):
        if _is_fuel(mat):
            fuel_mats.append(mat)
        elif _is_propellant_h2(mat):
            h2_mats.append(mat)
        elif _is_beo_reflector(mat):
            beo_mats.append(mat)
        else:
            other_mats.append(mat)

    def _print_group(title, mats, show_rho=True):
        if not mats:
            return
        print(f'    {title} ({len(mats)}):')
        # Stable ordering: by name, so layer indices come out in numeric order
        # for fuel_inner_layer_0, fuel_inner_layer_1, ...
        for mat in sorted(mats, key=lambda m: m.name or ''):
            T = mat.temperature
            line = f'      {(mat.name or "<unnamed>"):<32s}  T = {T:8.2f} K'
            if show_rho:
                line += f'   rho = {mat.density:.4e} g/cm3'
            print(line)

    _print_group('Fuel',          fuel_mats)
    _print_group('H2 propellant', h2_mats)
    _print_group('BeO reflector', beo_mats)
    # 'Other' materials (graphite, BeO supports, void, etc.) are never
    # perturbed by this script -- show them without density to keep the
    # block compact.
    _print_group('Other',         other_mats, show_rho=False)


# ---------------------------------------------------------------------------
# Model construction -- mirrors GCR_test.main() up to (but not including) .run()
# ---------------------------------------------------------------------------

def build_core(config, run_subdir):
    core = GCR(config)
    core.output_dir = os.path.join(RUNS_DIR, run_subdir)
    os.makedirs(core.output_dir, exist_ok=True)
    core.set_materials()
    if config.n_axial_layers > 1:
        core._create_layered_propellant_materials()
        core._create_layered_fuel_materials()

    # Scale fuel to the critical state BEFORE any perturbation is applied.
    # Matches main() in GCR_test.py.
    FUEL_DENSITY_ALPHA = 2.0240
    _seen = set()
    for mat in core.materials.values():
        if id(mat) in _seen:
            continue
        _seen.add(id(mat))
        name = mat.name or ''
        if (name == 'fuel' or name.startswith('fuel_inner')
                or name.startswith('fuel_outer')):
            mat.set_density('g/cm3', mat.density * FUEL_DENSITY_ALPHA)

    return core


def build_geometry_and_export(core):
    cfg = core.config

    core.build_cavity(tilt=cfg.tilt)

    sixty_deg = np.pi / 3
    hex_side_to_radius = 1.4
    hl  = cfg.r_inlet * hex_side_to_radius
    phi = 2 * cfg.tilt

    for i in range(6):
        y0 = hl * np.sin(sixty_deg) * (1 + np.cos(phi))
        z0 = hl * np.sin(sixty_deg) * np.sin(phi)
        theta = -i * np.pi / 3
        xp = -y0 * np.sin(theta)
        yp =  y0 * np.cos(theta)
        zp = z0
        core.build_cavity(
            x0=xp, y0=yp, z0=zp,
            tilt=cfg.tilt,
            cavity_angle_zz=theta,
            cavity_angle_xx=phi,
        )

    z_off = np.sin(sixty_deg) * hl / np.tan(phi)
    core.create_bounding_sphere(offset=z_off)
    core.build_moderator()
    core.build_end_moderator()
    core.build_nozzle_end()
    core.resolve_cavity_overlaps()
    core.set_source(batches=N_BATCHES, inactive=N_INACTIVE, n=N_PARTICLES)

    core.settings.temperature = {
        'method': 'interpolation',
        'tolerance': 300.0,
        'multipole': False,
    }
    core.settings.export_to_xml(os.path.join(core.output_dir, 'settings.xml'))

    core.export_geometry()

    # IFP kinetic-parameter tallies (β_eff, Λ_eff). Must be called AFTER
    # export_geometry() so the output directory already exists and after
    # set_source() so ifp_n_generation is already set in settings.
    if COLLECT_KINETIC_PARAMS:
        core.add_kinetics_tally(num_groups=6)


def _extract_keff_h5py(sp_path):
    """Fallback k_eff extractor that reads directly from the statepoint HDF5.

    Used when openmc.StatePoint cannot be opened because summary.h5 is absent
    or corrupt.  Kinetics parameters are not available via this path (they
    require tally linking which needs the summary), so an empty dict is
    returned for them.
    """
    import h5py
    with h5py.File(sp_path, 'r') as f:
        # 'k_combined' stores [mean, std_dev] of the combined k-eff estimator.
        k = f['k_combined'][()]
        nominal = float(k[0])
        stddev  = float(k[1])
    print('    [warn] k_eff extracted via h5py fallback '
          '(summary.h5 unavailable — kinetics parameters skipped).')
    return nominal, stddev, {}


def run_and_extract_keff(core):
    # Disable HDF5 POSIX file locking so summary.h5 can be written on NFS /
    # shared filesystems (prevents errno=11 "Resource temporarily unavailable").
    os.environ['HDF5_USE_FILE_LOCKING'] = 'FALSE'

    sp_path = os.path.join(core.output_dir, f'statepoint.{core.settings.batches}.h5')
    summary_path = os.path.join(core.output_dir, 'summary.h5')

    try:
        core.run(dry_run=False, map_geometry=False)
    except RuntimeError as e:
        # OpenMC can exit non-zero during teardown *after* the statepoint
        # is fully written. Treat that as success iff the file is readable.
        if not os.path.exists(sp_path):
            raise
        print(f'    [warn] OpenMC aborted on exit but statepoint exists — continuing. ({e})')

    # If summary.h5 exists but is corrupt (partial write from a prior locking
    # failure), remove it so StatePoint does not crash with
    # "bad object header version number".
    if os.path.exists(summary_path):
        try:
            import h5py as _h5
            _h5.File(summary_path, 'r').close()
        except OSError:
            print('    [warn] summary.h5 is corrupt — removing it before StatePoint open.')
            os.remove(summary_path)


    sp = openmc.StatePoint(sp_path)

    keff    = sp.keff
    nominal = float(keff.nominal_value)
    stddev  = float(keff.std_dev)

    kinetics = {}
    if COLLECT_KINETIC_PARAMS:
        kin = sp.get_kinetics_parameters()
        beta = kin.beta_effective      #total β_eff
        gen  = kin.generation_time     # Λ_eff in seconds
        kinetics['beta_eff']         = float(beta.nominal_value)
        kinetics['sigma_beta_eff']   = float(beta.std_dev)
        kinetics['gen_time_s']       = float(gen.nominal_value)
        kinetics['sigma_gen_time_s'] = float(gen.std_dev)


    sp.close()
    return nominal, stddev, kinetics


## Running the cases

def _tag(variable, delta):
    if variable == 'baseline':
        return 'baseline'
    if variable == 'fuel_T':
        sign = 'p' if delta >= 0 else 'm'
        return f'fuel_T_{sign}{abs(int(delta)):02d}K'
    if variable == 'h2_rho':
        sign = 'p' if delta >= 0 else 'm'
        return f'h2_rho_{sign}{abs(delta) * 100:02.0f}pct'
    if variable == 'fuel_rho':
        sign = 'p' if delta >= 0 else 'm'
        return f'fuel_rho_{sign}{abs(delta) * 100:02.0f}pct'
    if variable == 'beo_T':
        sign = 'p' if delta >= 0 else 'm'
        return f'beo_T_{sign}{abs(int(delta)):02d}K'
    if variable == 'h2_T':
        sign = 'p' if delta >= 0 else 'm'
        return f'h2_T_{sign}{abs(int(delta)):02d}K'
    if variable == 'fuel_radius':
        sign = 'p' if delta >= 0 else 'm'
        return f'fuel_radius_{sign}{abs(delta) * 100:02.0f}pct'
    raise ValueError(variable)


def run_case(variable, delta, base_config):
    """delta is in K for variable='fuel_T', dimensionless fraction for
    'h2_rho', 'fuel_rho', and 'power'."""
    tag = _tag(variable, delta)

    print(f'\n=== Case: {tag} ===')


    if variable == 'fuel_radius':
        # Scale R0, R1, R2 together so the internal cloud structure is preserved.
        # R3 (transparent wall) is left unchanged.
        R2_base = base_config.R2
        config_for_case = replace(
            base_config,
            R0=base_config.R0 * (1.0 + delta),
            R1=base_config.R1 * (1.0 + delta),
            R2=R2_base * (1.0 + delta),
        )
        R2_new = config_for_case.R2
        R3 = base_config.R3
        print(f'    R2: {R2_base:.4f} -> {R2_new:.4f} cm  '
              f'(gap to R3={R3:.2f} cm: {R3 - R2_new:.4f} cm)')
        if R2_new >= R3:
            raise ValueError(
                f'Perturbed R2 ({R2_new:.4f} cm) exceeds or meets the '
                f'transparent wall R3 ({R3:.4f} cm). Reduce the delta.'
            )
    elif variable not in ('fuel_radius',):
        config_for_case = base_config

    core = build_core(config_for_case, run_subdir=tag)

    if variable == 'fuel_T' and delta != 0.0:
        perturb_fuel_temperature(core, delta)          # kelvin, additive
    elif variable == 'h2_rho' and delta != 0.0:
        perturb_h2_density(core, 1.0 + delta)          # fractional, multiplicative
    elif variable == 'fuel_rho' and delta != 0.0:
        perturb_fuel_density(core, 1.0 + delta)        # fractional, multiplicative
    elif variable == 'beo_T' and delta != 0.0:
        perturb_beo_temperature(core, delta)           # kelvin, additive
    elif variable == 'h2_T' and delta != 0.0:
        perturb_h2_temperature(core, delta)            # kelvin, additive
    elif variable == 'fuel_radius' and delta != 0.0:
        # Volume scales as (1+delta)^2 → rescale density
        # to conserve total fuel inventory (constant number of U atoms).
        perturb_fuel_density(core, 1.0 / (1.0 + delta)**2)
        print_u233_mass_estimate(core.materials, config_for_case)

    # Validation: print the post-perturbation state of every material so
    # the user can confirm the sweep landed on the right materials with
    # the right shift before OpenMC spends an hour proving it ran.
    print_material_temperatures(core, label=tag)
    core.apply_beo_sab()
    build_geometry_and_export(core)
    keff, sigma, kinetics = run_and_extract_keff(core)

    print(f'    --> k_eff = {keff:.5f} +/- {sigma:.5f}')
    if kinetics:
        beta = kinetics.get('beta_eff')
        s_beta = kinetics.get('sigma_beta_eff', 0.0)
        gen  = kinetics.get('gen_time_s')
        s_gen = kinetics.get('sigma_gen_time_s', 0.0)
        print(f'    --> β_eff = {beta:.5f} +/- {s_beta:.5f}')
        print(f'    --> Λ_eff = {gen:.4e} +/- {s_gen:.4e} s')
        # reactivity in dollars (useful sanity check)
        if beta and beta > 0:
            rho_abs_pcm = 1e5 * (keff - 1.0) / keff
            print(f'    --> ρ / β_eff = {rho_abs_pcm / (beta * 1e5):+.4f} $')

    result = {
        'variable': variable,
        'delta':    float(delta),
        'keff':     float(keff),
        'sigma':    float(sigma),
        'tag':      tag
    }
    result.update(kinetics)   # adds beta_eff / sigma_beta_eff / gen_time_s / sigma_gen_time_s if collected
    return result


# ---------------------------------------------------------------------------
# Full scan + post-processing
# ---------------------------------------------------------------------------

def run_sensitivity_scan(mode='all', baseline_result=None):
    """Run the sweep(s) selected by `mode`.

    mode in {'all', 'fuel', 'h2', 'power', 'fuel_rho', 'beo', 'h2_T',
             'fuel_radius'}.
    Reactivity is always computed relative to a baseline case.

    Parameters
    ----------
    baseline_result : dict, optional
        A pre-computed baseline result dict (as produced by run_case()).
        When supplied the baseline OpenMC run is skipped entirely and this
        dict is used instead.  Pass this when the baseline has already been
        computed in a previous invocation to avoid re-running it for every
        partial sweep.  If None (default) the baseline is run as normal and
        a standalone copy is saved to <RESULTS_DIR>/baseline.json so it can
        be reused in future calls via load_baseline().
    """
    if mode not in ('all', 'fuel', 'h2', 'power', 'fuel_rho', 'beo', 'h2_T', 'fuel_radius'):
        raise ValueError(
            f"mode must be one of 'all', 'fuel', 'h2', 'power', 'fuel_rho', "
            f"'beo', 'h2_T', 'fuel_radius'; got {mode!r}"
        )

    os.makedirs(RESULTS_DIR, exist_ok=True)
    os.makedirs(RUNS_DIR,    exist_ok=True)

    base_config = GCRConfig(**BASE_CONFIG_KWARGS)

    results = []

    # Baseline — run only when not provided by the caller.
    if baseline_result is not None:
        print('\n=== Baseline: using pre-computed result (skipping OpenMC run) ===')
        print(f"    k_eff = {baseline_result['keff']:.5f} +/- {baseline_result['sigma']:.5f}")
        results.append(baseline_result)
    else:
        bl = run_case('baseline', 0.0, base_config)
        results.append(bl)
        # Persist a standalone copy so future partial sweeps can skip this run.
        bl_path = os.path.join(RESULTS_DIR, 'baseline.json')
        with open(bl_path, 'w') as _f:
            json.dump(bl, _f, indent=2)
        print(f'Baseline result saved to {bl_path}')

    # Fuel-temperature sweep (kelvin)
    if mode in ('all', 'fuel'):
        for dT in FUEL_T_DELTAS_K:
            results.append(run_case('fuel_T', dT, base_config))

    # H2 density sweep (fractional)
    if mode in ('all', 'h2'):
        for d_rho in H2_RHO_DELTAS:
            results.append(run_case('h2_rho', d_rho, base_config))


    # Fuel density sweep
    if mode in ('all', 'fuel_rho'):
        for d_rho_f in FUEL_RHO_DELTAS:
            results.append(run_case('fuel_rho', d_rho_f, base_config))

    # BeO reflector temperature sweep (kelvin)
    if mode in ('all', 'beo'):
        for dT in BEO_T_DELTAS_K:
            results.append(run_case('beo_T', dT, base_config))

    # H2 propellant temperature sweep (kelvin, additive).
    if mode in ('all', 'h2_T'):
        for dT in H2_T_DELTAS_K:
            results.append(run_case('h2_T', dT, base_config))

    # Fuel-cloud radius sweep (fractional change of R0/R1/R2, constant N_U
    if mode in ('all', 'fuel_radius'):
        for d_r in FUEL_RADIUS_DELTAS:
            results.append(run_case('fuel_radius', d_r, base_config))

    # Tag the output file by mode so partial runs don't clobber a full one.
    suffix = '' if mode == 'all' else f'_{mode}'
    out = os.path.join(RESULTS_DIR, f'keff_results{suffix}.json')
    with open(out, 'w') as f:
        json.dump(results, f, indent=2)
    print(f'\nRaw k_eff results written to {out}')

    return results


def _weighted_linear_fit(x, y, sy):
    """Weighted least-squares fit y = slope*x + intercept, weights = 1/sy^2.

    Returns (slope, intercept, slope_err, intercept_err).
    """
    x  = np.asarray(x,  float)
    y  = np.asarray(y,  float)
    sy = np.asarray(sy, float)
    w  = 1.0 / sy**2
    V  = np.vander(x, 2) # Vandermonde matrix such that V * a = y
    # w V a = w y
    # V_t w V a = V_t w y
    # a = (V_t w V)^-1 V_t w y
    # a is the vector with polynomial factors
    # https://en.wikipedia.org/wiki/Vandermonde_matrix
    cov = np.linalg.inv(V.T @ np.diag(w) @ V)  # weight the entries
    a = cov @ V.T @ (w * y)
    slope, intercept = float(a[0]), float(a[1])
    slope_err     = float(np.sqrt(cov[0, 0]))
    intercept_err = float(np.sqrt(cov[1, 1]))
    return slope, intercept, slope_err, intercept_err

def log_sensitivity(results, variable, ref_value=None):
    """UARL-style sensitivity coefficients SC = (δk/k)/(Δx/x₀).

    Check at J-910900-5, TABLE VI
    """
    baseline = next(r for r in results if r['variable'] == 'baseline')
    k_ref = baseline['keff']
    sub = [r for r in results if r['variable'] == variable]
    if len(sub) < 2:
        return None
    x  = [ (r['delta'] / ref_value if ref_value else r['delta']) for r in sub ]
    y  = [ (r['keff'] - k_ref) / k_ref for r in sub ]
    sy = [  r['sigma'] / k_ref          for r in sub ]
    S, _, S_err, _ = _weighted_linear_fit(x, y, sy)
    return S, S_err

def _rho_slope(results, variable):
    """dρ/d(delta) in pcm from stored k_eff — matches the existing fits.
    delta is a fraction for densities/radius (→ pcm per unit fraction)
    and kelvin for temperatures (→ pcm/K)."""
    sub = [r for r in results if r['variable'] == variable]
    if len(sub) < 2:
        return None
    x  = [r['delta']                          for r in sub]
    y  = [1e5 * (r['keff'] - 1.0) / r['keff'] for r in sub]
    sy = [1e5 * r['sigma'] / r['keff']**2     for r in sub]
    s, _, se, _ = _weighted_linear_fit(x, y, sy)
    return s, se


def practical_coefficient(results, variable):
    """Sensitivity coefficient in report units: densities → pcm/%, temperatures → pcm/K,
    fuel-cloud radius → pcm/mm.  Returns (value, err, unit) or None."""
    result = _rho_slope(results, variable)
    if result is None:
        return None
    slope, slope_error = result

    if variable in ('fuel_T', 'beo_T', 'h2_T'):
        return slope, slope_error, 'pcm/K'                    # delta already in K

    if variable in ('h2_rho', 'fuel_rho', 'power'):
        return slope / 100.0, slope_error / 100.0, 'pcm/%'    # divide by 100 to get %

    if variable == 'fuel_radius':
        R0_mm = GCRConfig(**BASE_CONFIG_KWARGS).R2 * 10.0   # length are defined in cm in openmc
        return slope / R0_mm, slope_error / R0_mm, 'pcm/mm'

    raise ValueError(f'unknown variable {variable!r}')

def compute_reactivity_and_plot(results):
    import csv
    import matplotlib.pyplot as plt

    for r in results:
        k_eff, sigma_k = r['keff'], r['sigma']
        r['rho_pcm'] = 1e5 * (k_eff - 1.0) / k_eff
        r['sigma_rho_pcm'] = 1e5 * sigma_k / k_eff**2

    # CSV ------------------------------------------------------------------
    csv_path = os.path.join(RESULTS_DIR, 'reactivity.csv')
    fieldnames = ['variable', 'delta', 'keff', 'sigma',
                  'rho_pcm', 'sigma_rho_pcm', 'tag',
                  'beta_eff', 'sigma_beta_eff', 'gen_time_s', 'sigma_gen_time_s']
    with open(csv_path, 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, extrasaction='ignore')
        w.writeheader()
        for r in results:
            w.writerow({k: r.get(k, '') for k in fieldnames})
    print(f'Reactivity table written to {csv_path}')

    # Console summary ------------------------------------------------------
    print('\n    variable    delta            k_eff              rho (pcm)')
    print('    --------    -------------   -----------------    ---------------')
    for r in results:
        if r['variable'] == 'fuel_T':
            d_str = f'{r["delta"]:+6.1f} K  '
        elif r['variable'] == 'h2_rho':
            d_str = f'{r["delta"]*100:+6.2f} %'
        elif r['variable'] == 'fuel_rho':
            d_str = f'{r["delta"]*100:+6.2f} %'
        elif r['variable'] == 'beo_T':
            d_str = f'{r["delta"]:+6.1f} K  '
        elif r['variable'] == 'h2_T':
            d_str = f'{r["delta"]:+6.1f} K  '
        elif r['variable'] == 'fuel_radius':
            d_str = f'{r["delta"]*GCRConfig(**BASE_CONFIG_KWARGS).R2:+6.1f} mm'
        else:
            d_str = '   --         '
        print(f'    {r["variable"]:<10s}  {d_str:<13s}   '
              f'{r["keff"]:.5f} +/- {r["sigma"]:.5f}    '
              f'{r["rho_pcm"]:+8.1f} +/- {r["sigma_rho_pcm"]:5.1f}')

    # Weighted linear fits (slope = sensitivity coefficient)
    print('\nReactivity coefficients (weighted linear fit):')

    baseline = next(r for r in results if r['variable'] == 'baseline')

    sub_T  = [r for r in results if r['variable'] == 'fuel_T']
    sub_H  = [r for r in results if r['variable'] == 'h2_rho']
    sub_F  = [r for r in results if r['variable'] == 'fuel_rho']
    sub_B  = [r for r in results if r['variable'] == 'beo_T']
    sub_HT = [r for r in results if r['variable'] == 'h2_T']
    sub_R = [r for r in results if r['variable'] == 'fuel_radius']

    fit_T = None
    if len(sub_T) >= 2:
        sT, iT, sT_err, iT_err = _weighted_linear_fit(
            [r['delta']         for r in sub_T],
            [r['rho_pcm']       for r in sub_T],
            [r['sigma_rho_pcm'] for r in sub_T],
        )
        fit_T = (sT, iT, sT_err, iT_err)
        print(f'  alpha_T   = {sT:+8.3f} +/- {sT_err:5.3f}  pcm/K')

    fit_H = None
    if len(sub_H) >= 2:
        sH, iH, sH_err, iH_err = _weighted_linear_fit(
            [r['delta']         for r in sub_H],
            [r['rho_pcm']       for r in sub_H],
            [r['sigma_rho_pcm'] for r in sub_H],
        )
        fit_H = (sH, iH, sH_err, iH_err)
        print(f'  alpha_rho = {sH:+8.3f} +/- {sH_err:5.3f}  '
              f'pcm / (delta_rho/rho_0)  (H2 density)')

    fit_F = None
    if len(sub_F) >= 2:
        alpha_rho_F, iF, alpha_rho_F_err, iF_err = _weighted_linear_fit(
            [r['delta']         for r in sub_F],
            [r['rho_pcm']       for r in sub_F],
            [r['sigma_rho_pcm'] for r in sub_F],
        )
        fit_F = (alpha_rho_F, iF, alpha_rho_F_err, iF_err)
        print(f'  alpha_rho_F = {alpha_rho_F:+8.3f} +/- {alpha_rho_F_err:5.3f}  pcm / (delta_rho/rho_0)  (fuel density, T fixed)')

    fit_B = None
    if len(sub_B) >= 2:
        sB, iB, sB_err, iB_err = _weighted_linear_fit(
            [r['delta']         for r in sub_B],
            [r['rho_pcm']       for r in sub_B],
            [r['sigma_rho_pcm'] for r in sub_B],
        )
        fit_B = (sB, iB, sB_err, iB_err)
        print(f'  alpha_BeO = {sB:+8.3f} +/- {sB_err:5.3f}  pcm/K   (BeO reflector temperature)')

    fit_HT = None
    if len(sub_HT) >= 2:
        sHT, iHT, sHT_err, iHT_err = _weighted_linear_fit(
            [r['delta']         for r in sub_HT],
            [r['rho_pcm']       for r in sub_HT],
            [r['sigma_rho_pcm'] for r in sub_HT],
        )
        fit_HT = (sHT, iHT, sHT_err, iHT_err)
        coupling_note = ('pure T, rho fixed')
        print(f'  alpha_T_H2 = {sHT:+8.3f} +/- {sHT_err:5.3f}  pcm/K   '
              f'(H2 propellant temperature, {coupling_note})')

    fit_R = None
    if len(sub_R) >= 2:

        sR, iR, sR_err, iR_err = _weighted_linear_fit(
            [r['delta'] for r in sub_R],
            [r['rho_pcm'] for r in sub_R],
            [r['sigma_rho_pcm'] for r in sub_R],
        )
        fit_R = (sR, iR, sR_err, iR_err)
        print(f'  alpha_R   = {sR:+8.3f} +/- {sR_err:5.3f}  '
              f'pcm / (delta_R/R0)  [mm/mm]  (fuel-cloud radius, N_U constant)')

    # ------------------------------------------------------------------ #
    # Panel layout helpers                                                  #
    # ------------------------------------------------------------------ #
    panels = []
    if sub_T:  panels.append('fuel_T')
    if sub_H:  panels.append('h2_rho')
    if sub_F:  panels.append('fuel_rho')
    if sub_B:  panels.append('beo_T')
    if sub_HT: panels.append('h2_T')
    if sub_R:  panels.append('fuel_radius')

    if not panels:
        print('No perturbation cases to plot.')
        return results

    n_panels = len(panels)

    # Shared figure-title suffix noting coupling assumptions.
    suptitle = 'GCR reactivity feedback'
    notes = []
    if sub_T:
        notes.append(r'pure Doppler: $\rho_\mathrm{fuel}$ held constant')
    if sub_HT:
        notes.append(r'H$_2$ $T$: $\rho_{\mathrm{H}_2}$ held constant')
    if notes:
        suptitle += '  (' + '; '.join(notes) + ')'

    # Layout: 1-3 panels in a single row; 4 panels 2x2; 5-6 panels 2x3.
    def _make_fig(n):
        if n <= 3:
            fig, axes = plt.subplots(1, n, figsize=(5.5 * n, 4.5), squeeze=False)
            flat = list(axes[0])
        elif n == 4:
            fig, axes = plt.subplots(2, 2, figsize=(11, 9), squeeze=False)
            flat = list(axes.flatten())
        else:
            fig, axes = plt.subplots(2, 3, figsize=(16.5, 9), squeeze=False)
            flat = list(axes.flatten())
            for ax in flat[n:]:
                ax.axis('off')
        return fig, axes, flat

    # ------------------------------------------------------------------ #
    # Figure 1 — absolute reactivity ρ = (k−1)/k  (pcm) vs perturbation  #
    # ------------------------------------------------------------------ #
    fig1, axes1, axes1_flat = _make_fig(n_panels)

    rho_baseline = baseline['rho_pcm']

    for ax, panel in zip(axes1_flat, panels):
        if panel == 'fuel_T':
            sub_sorted = sorted(sub_T, key=lambda r: r['delta'])
            x  = np.array([r['delta']         for r in sub_sorted])
            y  = np.array([r['rho_pcm']       for r in sub_sorted])
            ye = np.array([r['sigma_rho_pcm'] for r in sub_sorted])
            ax.errorbar(x, y, yerr=ye, marker='o', capsize=3,
                        linestyle='none', label='data')
            if fit_T is not None:
                sT, iT, sT_err, _ = fit_T
                xf = np.linspace(x.min(), x.max(), 50)
                ax.plot(xf, sT * xf + iT, 'k--', lw=1,
                        label=rf'$\alpha_T = {sT:+.2f} \pm {sT_err:.2f}$ pcm/K')
            ax.set_xlabel(r'$\Delta T_{\mathrm{fuel}}$ (K)')
            ax.set_title('Fuel temperature')
        elif panel == 'h2_rho':
            sub_sorted = sorted(sub_H, key=lambda r: r['delta'])
            x  = np.array([r['delta']         for r in sub_sorted])
            y  = np.array([r['rho_pcm']       for r in sub_sorted])
            ye = np.array([r['sigma_rho_pcm'] for r in sub_sorted])
            ax.errorbar(x, y, yerr=ye, marker='s', color='C1', capsize=3,
                        linestyle='none', label='data')
            if fit_H is not None:
                sH, iH, sH_err, _ = fit_H
                xf = np.linspace(x.min(), x.max(), 50)
                ax.plot(xf, sH * xf + iH, 'k--', lw=1,
                        label=rf'$\alpha_\rho = {sH:+.1f} \pm {sH_err:.1f}$ pcm/($\delta\rho/\rho_0$)')
            ax.set_xlabel(r'$\delta\rho_{\mathrm{H}_2} / \rho_{\mathrm{H}_2,0}$')
            ax.set_title(r'H$_2$ propellant density')
        elif panel == 'fuel_rho':
            sub_sorted = sorted(sub_F, key=lambda r: r['delta'])
            x  = np.array([r['delta']   for r in sub_sorted])
            y  = np.array([r['rho_pcm']       for r in sub_sorted])
            ye = np.array([r['sigma_rho_pcm'] for r in sub_sorted])
            ax.errorbar(x, y, yerr=ye, marker='D', color='C3', capsize=3,
                        linestyle='none', label='data')
            if fit_F is not None:
                alpha_rho_F, iF, alpha_rho_F_err, _ = fit_F
                xf = np.linspace(x.min(), x.max(), 50)
                ax.plot(xf, alpha_rho_F * xf + iF, 'k--', lw=1,
                        label=rf'$\alpha_{{\rho,F}} = {alpha_rho_F:+.2f} \pm {alpha_rho_F_err:.2f}$ pcm/($\delta\rho/\rho_0$)')
            ax.set_xlabel(r'$\delta\rho_{\mathrm{fuel}} / \rho_0$')
            ax.set_title('Fuel density (T fixed)')
        elif panel == 'beo_T':
            sub_sorted = sorted(sub_B, key=lambda r: r['delta'])
            x  = np.array([r['delta']         for r in sub_sorted])
            y  = np.array([r['rho_pcm']       for r in sub_sorted])
            ye = np.array([r['sigma_rho_pcm'] for r in sub_sorted])
            ax.errorbar(x, y, yerr=ye, marker='v', color='C4', capsize=3,
                        linestyle='none', label='data')
            if fit_B is not None:
                sB, iB, sB_err, _ = fit_B
                xf = np.linspace(x.min(), x.max(), 50)
                ax.plot(xf, sB * xf + iB, 'k--', lw=1,
                        label=rf'$\alpha_\mathrm{{BeO}} = {sB:+.2f} \pm {sB_err:.2f}$ pcm/K')
            ax.set_xlabel(r'$\Delta T_{\mathrm{BeO}}$ (K)')
            ax.set_title('BeO reflector temperature')
        elif panel == 'h2_T':
            sub_sorted = sorted(sub_HT, key=lambda r: r['delta'])
            x  = np.array([r['delta']         for r in sub_sorted])
            y  = np.array([r['rho_pcm']       for r in sub_sorted])
            ye = np.array([r['sigma_rho_pcm'] for r in sub_sorted])
            ax.errorbar(x, y, yerr=ye, marker='P', color='C5', capsize=3,
                        linestyle='none', label='data')
            if fit_HT is not None:
                sHT, iHT, sHT_err, _ = fit_HT
                xf = np.linspace(x.min(), x.max(), 50)
                ax.plot(xf, sHT * xf + iHT, 'k--', lw=1,
                        label=rf'$\alpha_{{T,\mathrm{{H}}_2}} = {sHT:+.2f} \pm {sHT_err:.2f}$ pcm/K')
            ax.set_xlabel(r'$\Delta T_{\mathrm{H}_2}$ (K)')
            ax.set_title(r'H$_2$ propellant temperature')
        else:  # fuel_radius
            sub_sorted = sorted(sub_R, key=lambda r: r['delta'])
            x  = np.array([r['delta']         for r in sub_sorted])
            y  = np.array([r['rho_pcm']       for r in sub_sorted])
            ye = np.array([r['sigma_rho_pcm'] for r in sub_sorted])
            ax.errorbar(x, y, yerr=ye, marker='h', color='C6', capsize=3,
                        linestyle='none', label='data')
            if fit_R is not None:
                sR, iR, sR_err, _ = fit_R
                xf = np.linspace(x.min(), x.max(), 50)
                ax.plot(xf, sR * xf + iR, 'k--', lw=1,
                        label=rf'$\alpha_R = {sR:+.1f} \pm {sR_err:.1f}$ pcm/(mm/mm)')
            ax.set_xlabel(r'$\delta R / R_0$  [mm/mm]')
            ax.set_title(r'Fuel-cloud radius ($N_U$ const)')

        # Baseline reference line
        ax.axhline(rho_baseline, color='grey', lw=0.8, linestyle=':',
                   label=rf'$\rho_{{\mathrm{{ref}}}} = {rho_baseline:.0f}$ pcm')
        ax.axvline(0, color='k', lw=0.5)
        ax.grid(alpha=0.3)
        ax.legend(fontsize=8)

    # Y-label on leftmost axes in each row.
    ylabel_rho = r'Reactivity $\rho = (k-1)/k$ (pcm)'
    if n_panels <= 3:
        axes1_flat[0].set_ylabel(ylabel_rho)
    else:
        axes1[0, 0].set_ylabel(ylabel_rho)
        axes1[1, 0].set_ylabel(ylabel_rho)

    fig1.suptitle(suptitle)
    fig1.tight_layout()

    plot_suffix = '_' + '_'.join(panels) if len(panels) < 6 else ''
    pdf1 = os.path.join(RESULTS_DIR, f'reactivity{plot_suffix}.pdf')
    fig1.savefig(pdf1, dpi=150)
    print(f'Reactivity plot written to {pdf1}')

    # ------------------------------------------------------------------ #
    # Figure 2 — absolute k_eff vs perturbation                            #
    # ------------------------------------------------------------------ #
    fig2, axes2, axes2_flat = _make_fig(n_panels)

    k_baseline  = baseline['keff']
    sk_baseline = baseline['sigma']

    _panel_subs = {
        'fuel_T':      (sub_T,  sub_T  and sorted(sub_T,  key=lambda r: r['delta']), 'o', 'C0', r'$\Delta T_{\mathrm{fuel}}$ (K)',              'Fuel temperature'),
        'h2_rho':      (sub_H,  sub_H  and sorted(sub_H,  key=lambda r: r['delta']), 's', 'C1', r'$\delta\rho_{\mathrm{H}_2} / \rho_{\mathrm{H}_2,0}$', r'H$_2$ propellant density'),
        'fuel_rho':    (sub_F,  sub_F  and sorted(sub_F,  key=lambda r: r['delta']), 'D', 'C3', r'$\Delta $\delta\ldots/\ldots_0$',            'Fuel density (T fixed)'),
        'beo_T':       (sub_B,  sub_B  and sorted(sub_B,  key=lambda r: r['delta']), 'v', 'C4', r'$\Delta T_{\mathrm{BeO}}$ (K)',                'BeO reflector temperature'),
        'h2_T':        (sub_HT, sub_HT and sorted(sub_HT, key=lambda r: r['delta']), 'P', 'C5', r'$\Delta T_{\mathrm{H}_2}$ (K)',               r'H$_2$ propellant temperature'),
        'fuel_radius': (sub_R,  sub_R  and sorted(sub_R,  key=lambda r: r['delta']), 'h', 'C6', r'$\delta R / R_0$  [mm/mm]',                   r'Fuel-cloud radius ($N_U$ const)'),
    }

    for ax, panel in zip(axes2_flat, panels):
        _, sub_sorted, mk, col, xlabel, title = _panel_subs[panel]
        scale = 1.0
        x  = np.array([scale * r['delta'] for r in sub_sorted])
        y  = np.array([r['keff']          for r in sub_sorted])
        ye = np.array([r['sigma']         for r in sub_sorted])
        ax.errorbar(x, y, yerr=ye, marker=mk, color=col, capsize=3,
                    linestyle='none', label='data')
        # Baseline reference
        ax.errorbar([0], [k_baseline], yerr=[sk_baseline],
                    marker='*', color='grey', capsize=3, markersize=9,
                    linestyle='none', label=rf'baseline $k={k_baseline:.5f}$')
        ax.axhline(1.0, color='k', lw=0.8, linestyle='--', label=r'$k_\mathrm{eff}=1$')
        ax.set_xlabel(xlabel)
        ax.set_title(title)
        ax.grid(alpha=0.3)
        ax.legend(fontsize=8)

    ylabel_k = r'$k_\mathrm{eff}$'
    if n_panels <= 3:
        axes2_flat[0].set_ylabel(ylabel_k)
    else:
        axes2[0, 0].set_ylabel(ylabel_k)
        axes2[1, 0].set_ylabel(ylabel_k)

    fig2.suptitle(suptitle.replace('reactivity feedback', r'$k_\mathrm{eff}$'))
    fig2.tight_layout()

    pdf2 = os.path.join(RESULTS_DIR, f'keff{plot_suffix}.pdf')
    fig2.savefig(pdf2, dpi=150)
    print(f'k_eff plot written to {pdf2}')

    # ------------------------------------------------------------------ #
    # Figure 3 — kinetic parameters (β_eff, Λ_eff) if collected          #
    # ------------------------------------------------------------------ #
    has_kinetics = any('beta_eff' in r for r in results)
    if has_kinetics:
        plot_kinetic_parameters(results, panels, suptitle)

    plt.show()
    return results

# Baseline ABSOLUTE temperatures [K] for the UARL dimensionless S of the
# thermal vars. Set these to your unperturbed run's values. fuel_T is left
# out on purpose — no single T₀ on the 15–20 kK radiation-equilibrium profile.
_T_REF_K = {
    'beo_T': 1698.33,
    'h2_T':  6670.0,
}

def print_coefficient_summary(results):
    order = ['fuel_T', 'h2_rho', 'fuel_rho', 'beo_T', 'h2_T', 'fuel_radius']
    print('\n  variable       UARL S=(δk/k)/(Δx/x₀)      practical')
    print('  ----------     ----------------------     --------------------')
    for v in order:
        prac = practical_coefficient(results, v)
        if prac is None:
            continue
        val, err, unit = prac

        if v in ('h2_rho', 'fuel_rho', 'power', 'fuel_radius'):
            S = log_sensitivity(results, v)                       # delta already Δx/x₀
        elif v in _T_REF_K:
            S = log_sensitivity(results, v, ref_value=_T_REF_K[v])
        else:
            S = None                                             # fuel_T: no single T₀

        s_str = f'{S[0]:+.4f} ± {S[1]:.4f}' if S else '        —'
        print(f'  {v:<12s}   {s_str:>20s}      {val:+8.3f} ± {err:.3f} {unit}')

def plot_kinetic_parameters(results, panels, suptitle='GCR kinetic parameters'):
    """Plot β_eff and Λ_eff vs perturbation parameter for every sweep variable.

    Called automatically from compute_reactivity_and_plot() when kinetics
    data are present. Can also be called directly on a loaded results list.

    Parameters
    ----------
    results   : list[dict]  – same structure as returned by run_sensitivity_scan()
    panels    : list[str]   – ordered list of variable names (e.g. ['fuel_T', 'h2_rho'])
    suptitle  : str         – figure super-title (coupling-assumption note appended)
    """
    import matplotlib.pyplot as plt

    if not any('beta_eff' in r for r in results):
        print('No kinetic parameters in results (COLLECT_KINETIC_PARAMS was False).')
        return

    # Variable metadata: (subset_list, x_scale, xlabel, marker, color)
    _meta = {
        'fuel_T':   ([r for r in results if r['variable'] == 'fuel_T'],
                     1.0,   r'$\Delta T_{\mathrm{fuel}}$ (K)',      'o', 'C0'),
        'h2_rho':   ([r for r in results if r['variable'] == 'h2_rho'],
                     1.0,   r'$\delta\rho_{\mathrm{H}_2} / \rho_{\mathrm{H}_2,0}$', 's', 'C1'),
        'fuel_rho': ([r for r in results if r['variable'] == 'fuel_rho'],
                     100.0, r'$\Delta \rho_{\mathrm{fuel}}$ (%)',    'D', 'C3'),
        'beo_T':    ([r for r in results if r['variable'] == 'beo_T'],
                     1.0,   r'$\Delta T_{\mathrm{BeO}}$ (K)',        'v', 'C4'),
        'h2_T':     ([r for r in results if r['variable'] == 'h2_T'],
                     1.0,   r'$\Delta T_{\mathrm{H}_2}$ (K)',        'P', 'C5'),
        'fuel_radius': ([r for r in results if r['variable'] == 'fuel_radius'],
                        1.0,   r'$\delta R / R_0$  [mm/mm]',                   'h', 'C6'),
    }

    n_panels = len(panels)
    if n_panels == 0:
        return

    def _make_fig(n):
        if n <= 3:
            fig, axes = plt.subplots(2, n, figsize=(5.5 * n, 9), squeeze=False)
        elif n == 4:
            fig, axes = plt.subplots(4, 2, figsize=(11, 18), squeeze=False)
        else:
            fig, axes = plt.subplots(4, 3, figsize=(16.5, 18), squeeze=False)
            for ax in axes.flatten()[2 * n:]:
                ax.axis('off')
        return fig, axes

    fig, axes = _make_fig(n_panels)

    # Row 0: β_eff  |  Row 1: Λ_eff  (repeated for 4-panel+ layouts)
    if n_panels <= 3:
        beta_axes  = axes[0]   # shape (n_panels,)
        gen_axes   = axes[1]
    else:
        # Flatten and slice manually for generality
        flat = axes.flatten()
        beta_axes = flat[:n_panels]
        gen_axes  = flat[n_panels:2 * n_panels]

    baseline = next((r for r in results if r['variable'] == 'baseline'), None)
    beta_ref = baseline.get('beta_eff') if baseline else None
    gen_ref  = baseline.get('gen_time_s') if baseline else None

    for i, panel in enumerate(panels):
        sub, scale, xlabel, mk, col = _meta[panel]
        sub_sorted = sorted(sub, key=lambda r: r['delta'])

        x  = np.array([scale * r['delta'] for r in sub_sorted])
        b  = np.array([r.get('beta_eff', np.nan)         for r in sub_sorted])
        sb = np.array([r.get('sigma_beta_eff', 0.0)      for r in sub_sorted])
        g  = np.array([r.get('gen_time_s', np.nan)       for r in sub_sorted])
        sg = np.array([r.get('sigma_gen_time_s', 0.0)    for r in sub_sorted])

        # β_eff panel
        ax_b = beta_axes[i]
        ax_b.errorbar(x, b * 1e3, yerr=sb * 1e3,  # display in units of 1e-3
                      marker=mk, color=col, capsize=3, linestyle='none', label='data')
        if beta_ref is not None:
            ax_b.axhline(beta_ref * 1e3, color='grey', lw=0.8, linestyle=':',
                         label=rf'baseline $\beta = {beta_ref*1e3:.2f} \times 10^{{-3}}$')
        ax_b.set_xlabel(xlabel)
        ax_b.set_ylabel(r'$\beta_\mathrm{eff}$ ($\times 10^{-3}$)')
        ax_b.set_title(f'β_eff — {panel.replace("_", " ")}')
        ax_b.grid(alpha=0.3)
        ax_b.legend(fontsize=8)

        # Λ_eff panel
        ax_g = gen_axes[i]
        ax_g.errorbar(x, g * 1e6, yerr=sg * 1e6,  # display in µs
                      marker=mk, color=col, capsize=3, linestyle='none', label='data')
        if gen_ref is not None:
            ax_g.axhline(gen_ref * 1e6, color='grey', lw=0.8, linestyle=':',
                         label=rf'baseline $\Lambda = {gen_ref*1e6:.2f}$ µs')
        ax_g.set_xlabel(xlabel)
        ax_g.set_ylabel(r'$\Lambda_\mathrm{eff}$ (µs)')
        ax_g.set_title(rf'$\Lambda_\mathrm{{eff}}$ — {panel.replace("_", " ")}')
        ax_g.grid(alpha=0.3)
        ax_g.legend(fontsize=8)

    fig.suptitle(suptitle.replace('reactivity feedback', 'kinetic parameters'))
    fig.tight_layout()

    plot_suffix = '_' + '_'.join(panels) if len(panels) < 6 else ''
    pdf3 = os.path.join(RESULTS_DIR, f'kinetics{plot_suffix}.pdf')
    fig.savefig(pdf3, dpi=150)
    print(f'Kinetic parameters plot written to {pdf3}')
    return fig


def load_baseline(results_path=None):
    """Load a pre-computed baseline result from a JSON file.

    Accepts either a standalone baseline.json (a single dict) or any
    keff_results*.json list — the first entry whose 'variable' is 'baseline'
    is returned.

    Parameters
    ----------
    results_path : str, optional
        Path to a JSON file.  Defaults to <RESULTS_DIR>/baseline.json.

    Returns
    -------
    dict
        The baseline result dict, ready to pass as ``baseline_result`` to
        :func:`run_sensitivity_scan`.

    Raises
    ------
    FileNotFoundError
        If the file does not exist.
    ValueError
        If no baseline entry is found in the file.
    """
    if results_path is None:
        results_path = os.path.join(RESULTS_DIR, 'baseline.json')

    if not os.path.exists(results_path):
        raise FileNotFoundError(
            f'No baseline file at {results_path!r}. '
            f'Run a sweep without --baseline-json first so the file is created, '
            f'or point --baseline-json at an existing keff_results*.json.'
        )

    with open(results_path, 'r') as f:
        data = json.load(f)

    # Support both a bare dict (standalone baseline.json) and a list
    # (keff_results*.json with multiple entries).
    if isinstance(data, dict):
        if data.get('variable') != 'baseline':
            raise ValueError(
                f'{results_path!r} is a dict but its "variable" field is '
                f'{data.get("variable")!r}, not "baseline".'
            )
        return data

    # It's a list — find the first baseline entry.
    for entry in data:
        if entry.get('variable') == 'baseline':
            print(f'Loaded baseline from {results_path!r}  '
                  f'(k_eff = {entry["keff"]:.5f} +/- {entry["sigma"]:.5f})')
            return entry

    print(f'Loaded {len(results)} cases from {results_path}')
    return compute_reactivity_and_plot(results)

def extend_h2_T_scan(extra_deltas, results_path=None):
    """Run additional h2_T cases and merge them into an existing results file.

    Skips any delta already present and skips the baseline rerun -- much
    cheaper than re-running the whole sweep.

    Parameters
    ----------
    extra_deltas : iterable of float
        Additional ΔT values in kelvin to evaluate (e.g. [-2000, +2000]).
    results_path : str, optional
        JSON file to extend. Defaults to <RESULTS_DIR>/keff_results_h2_T.json.

    Returns
    -------
    list[dict]
        The merged results list (baseline + all h2_T points), suitable
        for handing straight to compute_reactivity_and_plot().
    """
    if results_path is None:
        results_path = os.path.join(RESULTS_DIR, 'keff_results_h2_T.json')

    if not os.path.exists(results_path):
        raise FileNotFoundError(
            f'No cached results at {results_path!r}. '
            f'Run the h2_T sweep first.'
        )

    with open(results_path, 'r') as f:
        results = json.load(f)

    # Sanity check: coupling flag must match the original scan, otherwise
    # the new points are not on the same curve as the existing ones.
    existing_h2T = [r for r in results if r['variable'] == 'h2_T']

    existing_deltas = {round(r['delta'], 6) for r in existing_h2T}

    base_config = GCRConfig(**BASE_CONFIG_KWARGS)

    for dT in extra_deltas:
        if round(float(dT), 6) in existing_deltas:
            print(f'h2_T ΔT = {dT:+g} K already in results, skipping')
            continue
        results.append(run_case('h2_T', float(dT), base_config))

    with open(results_path, 'w') as f:
        json.dump(results, f, indent=2)
    print(f'Extended results written to {results_path}')

    return results

# ---------------------------------------------------------------------------

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(
        description='GCR reactivity-feedback sensitivity scan.'
    )
    parser.add_argument(
        '--mode',
        choices=('all', 'fuel', 'h2', 'fuel_rho', 'beo', 'h2_T',
                 'extend_h2_T', 'fuel_radius'),
        default='all',
        help="Which sweep(s) to run. 'extend_h2_T' adds extra ΔT points "
             "(see --extra-deltas) to an existing keff_results_h2_T.json "
             "instead of running a full sweep.",
    )
    parser.add_argument(
        '--extra-deltas',
        type=float,
        nargs='+',
        default=[-2000.0, +2000.0],
        help='ΔT values in K for --mode extend_h2_T (default: -2000 +2000).',
    )
    parser.add_argument(
        '--baseline-json',
        metavar='PATH',
        default=None,
        help=(
            'Path to a JSON file containing a pre-computed baseline result '
            '(either a standalone baseline.json produced by a previous run, '
            'or any keff_results*.json list).  When supplied the baseline '
            'OpenMC simulation is skipped entirely, saving ~6 hours per '
            'partial sweep.  Omit to run (and save) the baseline as normal.'
        ),
    )
    args = parser.parse_args()

    # Load a pre-computed baseline if the caller supplied one.
    baseline_result = None
    if args.baseline_json is not None:
        baseline_result = load_baseline(args.baseline_json)

    if args.mode == 'extend_h2_T':
        results = extend_h2_T_scan(args.extra_deltas)
    else:
        # noinspection PyInterpreter
        results = run_sensitivity_scan(mode=args.mode,
                                       baseline_result=baseline_result)

    compute_reactivity_and_plot(results)
    print_coefficient_summary(results)